#pragma once

#include "MIR_Structs.h"

// Void
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 0, void)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 1, void*)

// Mutable
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 2, signed char)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 3, signed short)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 4, signed int)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 5, signed long long)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 6, unsigned char)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 7, unsigned short)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 8, unsigned int)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 9, unsigned long long)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 10, float)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 11, double)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 12, long double)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 13, char)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 14, bool)

// Const
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 15, const signed char)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 16, const signed short)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 17, const signed int)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 18, const signed long long)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 19, const unsigned char)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 20, const unsigned short)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 21, const unsigned int)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 22, const unsigned long long)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 23, const float)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 24, const double)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 25, const long double)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 26, const char)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 27, const bool)

// Mutable pointers
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 28, signed char*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 29, signed short*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 30, signed int*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 31, signed long long*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 32, unsigned char*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 33, unsigned short*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 34, unsigned int*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 35, unsigned long long*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 36, float*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 37, double*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 38, long double*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 39, char*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 40, bool*)

// Const pointers
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 41, const signed char*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 42, const signed short*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 43, const signed int*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 44, const signed long long*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 45, const unsigned char*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 46, const unsigned short*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 47, const unsigned int*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 48, const unsigned long long*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 49, const float*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 50, const double*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 51, const long double*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 52, const char*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 53, const bool*)

// String
#include <string>
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 54, std::string)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 55, std::string*)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 56, const std::string)
MIRROR_TYPE_ID(MIRROR_FIELD_ID_SIZE_MAX - 57, const std::string*)

#define MIRROR_USER_TYPE_ID_MAX MIRROR_FIELD_ID_SIZE_MAX - 58
